import { Inter } from 'next/font/google'
import './globals.css'
import SiteNavbar from '@/components/SiteNavbar'
import SiteFooter from '@/components/SiteFooter'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      {/* <NextTopLoader color="#269669" height={3} speed={200} /> */}
        <SiteNavbar/>
        {children}
        <SiteFooter/>
        </body>
    </html>
  )
}
